# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModFavorite',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='favorite.Favorite')),
            ],
            bases=('favorite.favorite',),
        ),
    ]
